# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fb82f297367827189a00f07df81224a09d64533e2e8611f49a83655b38deb98da9dbec83fd65e611ad055feebce78351027910360a3f6587f4b3fb95ec60d659

test:
  secret_key_base: 9c147e1068f2dbc646db9c11209cd1aacf837992977e271712c96b574a159eebb0fe2f703fc2cc03378a7c29385bfe17179c01d33cba60addf33bf074f7030fa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
